#server:
#  port: 8089

spring:
  cloud:
    nacos:
      discovery:
        server-addr:
          localhost:8848
  application:
    name:
      service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

Amap:
  key: "9e8f8ea4ba4cd6a55bfcd54d8b869f80"
  sid: 1009278

---
spring:
  profiles: 8007
server:
  port: 8007

---
---
spring:
  profiles: 8008
server:
  port: 8008